name: API Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run tests
        run: mvn clean test

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/allure-report

  deploy:
    needs: api-tests
    if: always()
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
